In [1]:
ls

 Volume in drive C has no label.
 Volume Serial Number is E490-BF90

 Directory of C:\Users\Dale_Lo\DM\TKU-DM-610630112

2022/09/29  ?? 10:21    <DIR>          .
2022/09/29  ?? 10:21    <DIR>          ..
2022/09/29  ?? 10:21    <DIR>          .ipynb_checkpoints
2022/09/22  ?? 11:06             4,206 0915-1.ipynb
2022/09/22  ?? 11:38             7,952 0922.ipynb
2022/09/29  ?? 10:21               589 0929.ipynb
2022/09/22  ?? 11:46                85 git??.txt
2022/09/22  ?? 11:06             1,290 hello.ipynb
2022/09/22  ?? 11:06                18 README.md
2022/09/22  ?? 11:38           152,262 scores.csv
               7 File(s)        166,402 bytes
               3 Dir(s)  253,383,888,896 bytes free


In [2]:
run hello.ipynb

hello world


In [5]:
%%writefile hi.py
print("Hi 0929!!!")
#新增檔案

Overwriting hi.py


In [6]:
a = 1

In [7]:
b = 2

In [8]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [11]:
pip install Numpy

  Using cached numpy-1.23.3-cp310-cp310-win_amd64.whl (14.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np #縮寫numpy成np

In [13]:
np1 = np.array([1,2,3,4])

In [14]:
np2 = np.array((5,6,7,8))

In [15]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [16]:
np3 = np.arange(0,31,2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [17]:
np4 = np.linspace(1,15,3)#1~15拆3等分
print(np4)

[ 1.  8. 15.]


In [18]:
np4 = np.linspace(1,10,10)#1~10拆10等分
print(np4)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [19]:
np5 = np.zeros((5,))#填充zero五次
print(np5)

[0. 0. 0. 0. 0.]


In [20]:
np6 = np.ones((5,))
print(np6)

[1. 1. 1. 1. 1.]


In [21]:
np7 = np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
np7 = np.ones((5,3))
print(np7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
listdata = [[1,2,3,4,5],
            [6,7,8,9,10]]
print(listdata)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [25]:
np8 = np.array(listdata)

In [28]:
np8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
print(np8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
print('維度',np8.ndim)

維度 2


In [33]:
print("形狀",np8.shape)

形狀 (2, 5)


In [34]:
print("數量",np8.size)

數量 10


In [36]:
np9 = np.arange(1,21)
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
print(np9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [38]:
np10 = np9.reshape(4,5)
np10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [41]:
np10a = np9.reshape(5,4)
np10a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [43]:
np10 = np.arange(0,9)
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[:4])
print(np10[4:])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3]
[4 5 6 7 8]


In [44]:
np11 = np.arange(1,21).reshape(5,4)
np11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
np11[0,2]

3

In [46]:
np11[0,3]

4

In [47]:
np11[1,2]

7

In [54]:
print(np11[1:3,2])

[ 7 11]


In [49]:
print(np11[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [50]:
print(np11[::2,::2])

[[ 1  3]
 [ 9 11]
 [17 19]]


In [51]:
print(np11[:,2])

[ 3  7 11 15 19]


In [52]:
print(np11[1,:])

[5 6 7 8]


In [53]:
print(np11[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [59]:
print('1.產生2x30~1之間的隨機浮數\n',
np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
np.random.randint(2,5,[5]))
print('5.產生3個0~1之間的隨機浮點數\n',
np.random.random(3), '\n',
np.random.random_sample(3), '\n',
np.random.sample(3))

1.產生2x30~1之間的隨機浮數
 [[0.67841822 0.76827518 0.96072332]
 [0.4814122  0.12290021 0.72803784]]
2.產生2x3常態分佈的隨機浮點數
 [[-0.43065557 -0.44664504 -0.56431926]
 [ 1.57325837  2.1983818  -1.16780529]]
3.產生0~4(不含5)隨機整數
 0
4.產生2~4(不含5)5個隨機整數
 [2 4 4 2 4]
5.產生3個0~1之間的隨機浮點數
 [0.22431041 0.19232136 0.8957325 ] 
 [1.14366400e-01 5.83424188e-04 7.31596633e-01] 
 [0.54036198 0.04486919 0.7961077 ]


In [57]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [58]:
print(np12)

[[ 1. 87. 85. 82.]
 [ 2. 92. 87. 90.]
 [ 3. 80. 91. 87.]
 [ 4. 78. 82. 95.]
 [ 5. 88. 89. 90.]
 [ 6. 82. 87. 88.]
 [ 7. 90. 92. 82.]
 [ 8. 87. 80. 90.]
 [ 9. 95. 78. 87.]
 [10. 90. 88. 95.]
 [11. 88. 89. 75.]
 [12. 82. 91. 66.]
 [13. 90. 82. 87.]
 [14. 87. 89. 92.]
 [15. 95. 87. 80.]
 [16. 90. 92. 78.]
 [17. 82. 80. 88.]
 [18. 90. 78. 93.]
 [19. 67. 87. 95.]
 [20. 91. 82. 88.]
 [21. 82. 81. 82.]
 [22. 79. 87. 90.]
 [23. 87. 92. 87.]
 [24. 92. 82. 95.]
 [25. 80. 90. 78.]
 [26. 78. 76. 91.]
 [27. 66. 90. 82.]
 [28. 89. 77. 89.]
 [29. 87. 95. 87.]
 [30. 73. 90. 92.]]


In [62]:
np13 = np.genfromtxt('432.csv', delimiter=',', skip_header=1)
np13

array([[1.00000000e-01, 7.00000000e+00, 1.60000000e+01, 0.00000000e+00,
        1.21760056e+02, 2.51291670e+01, 1.00000000e+00],
       [1.00000000e-01, 7.00000000e+00, 1.30000000e+01, 0.00000000e+00,
        1.21642300e+02, 2.50671310e+01, 2.00000000e+00],
       [1.00000000e-01, 7.00000000e+00, 1.80000000e+01, 0.00000000e+00,
        1.21689881e+02, 2.51796670e+01, 3.00000000e+00],
       [2.00000000e-01, 4.00000000e+00, 8.00000000e+00, 0.00000000e+00,
        1.21537778e+02, 2.49772220e+01, 4.00000000e+00],
       [3.00000000e-01, 4.00000000e+00, 1.60000000e+01, 0.00000000e+00,
        1.21451861e+02, 2.49825280e+01, 5.00000000e+00],
       [2.00000000e-01, 7.00000000e+00, 1.30000000e+01, 1.00000000e+00,
        1.21458667e+02, 2.50129720e+01, 6.00000000e+00],
       [2.00000000e-01, 9.00000000e+00, 2.30000000e+01, 0.00000000e+00,
        1.21432500e+02, 2.50379720e+01, 7.00000000e+00],
       [2.00000000e-01, 8.00000000e+00, 1.60000000e+01, 0.00000000e+00,
        1.21481028e+02, 2